apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orchestrator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: orchestrator-role-binding
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: orchestrator-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      serviceAccountName: orchestrator-sa
      containers:
        - name: orchestrator
          image: lalit0708/replit-orchestrator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          env:
            - name: CLUSTER_DOMAIN
              value: "ae41f1ac253364a678139871a7f94967-347610126.ap-south-1.elb.amazonaws.com" # Updated automatically
            - name: FRONTEND_URL
              value: "https://replit-puce.vercel.app"
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
